# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  local:
    dir: ./sample/src/app
    env:
      AUDIENCE: "k3d Demoists"
      SOMENAME: "My own name"
    cmds:
      - flask run
